### ISSUE TITLE
new returns undef when only a single set is passed

### ISSUE THREAD

**Issue by abraxxa** [briandfoy/set-crossproduct#5]
Why is this (edge) case not handled?
https://github.com/briandfoy/set-crossproduct/blob/master/lib/Set/CrossProduct.pm#L214

Please at least document that new can return undef or throw an exception instead. That would be my preferred API.

Thanks!

**Comment by briandfoy** [comment]
I've documented it and added warnings when things are weird. thanks! 2.005 is on its way to CPAN.

**Comment by abraxxa** [comment]
I‘ve emulated support for that case to not need a completely separate code path. Would you be willing to add support for it?

**Comment by briandfoy** [comment]
Sure, I'll take a look.

**Comment by abraxxa** [comment]
That's my current code:
```
    my $crossproduct = Set::CrossProduct->new(\%match_criteria);
    my @tuples;
    my $cardinality;
    # two or more match criteria
    if (defined $crossproduct) {
        $cardinality = $crossproduct->cardinality;
        @tuples = $crossproduct->combinations;
    }
    # one match criteria
    else {
        die "not one match criteria: " . scalar @match_keys
            unless @match_keys == 1;
        # emulate Set::Crossproduct->combinations output
        @tuples = ( { $match_keys[0] => $match_criteria{$match_keys[0]}->[0] });
        $cardinality = @tuples;
    }
```

**Comment by briandfoy** [comment]
I can't quite work it into the module. I tried that and lots of things fail because the rest of the interface needs to work too. I also noted in the tests that I explicitly test that the one array case is an error. I don't want to break this for anyone who depended on that.

Not only that, with one set, I'd basically have to redo everything. Algorithm::NestedLoops or one of the other modules might work out better for you.

Also, I think your workaround might be simpler with something like this, where you check the number of keys and then decide what to do. It looks like you are accounting for the possibility that you might have 0 keys, so I think this is simpler. 

Some of the details here are wrong (like, I don't know why you only take the first item in the value array), but basically you are getting all the combinations at once. You can get the cardinality later by looking at the number of tuples you have. 

```
my $tuples = do {
	     if( 1 == keys %match_criteria ) { [ \%match_criteria ] }
	elsif( 1 <   keys %match_criteria ) { Set::CrossProduct->new(\%match_criteria)->combinations }
	else { die ... }
	};
	
my $cardinality = @$tuples;
```

**Comment by abraxxa** [comment]
I couldn't find Algorithm::NestedLoops on CPAN, did you mean [Algorithm::Loops](https://metacpan.org/pod/Algorithm::Loops)?

**Comment by briandfoy** [comment]
I guess it's  Algorithm::Loops that has the NestedLoops function.

**Comment by abraxxa** [comment]
Thanks for pointing out my oversight regarding a single match criteria with multiple elements!
I haven't had this case until yesterday and fixed it based on your comment.
